### ISSUE TITLE
Field: Full Name

### ISSUE THREAD

**Issue by micahchiang** [department-of-veterans-affairs/va-forms-system-core#218] opened 2022-03-29 21:08 UTC
## Description
Many forms on VA.gov ask for a person's full name. This includes first name, middle initial, last name, and suffix, with first and last name being required fields. 

<details><summary>Full Name UI</summary>

![Screen Shot 2022-03-29 at 3.53.49 PM.png](https://images.zenhubusercontent.com/5d68043b330f64311395e92b/f4d5d52a-f555-446b-85e2-473ac7e673da)
</details>

From a high level, using existing va-forms-system-core fields, a `FullNameField` may have a structure that looks like this:
```
const FullNameField = (props: FullNameProps<string>): JSX.Element => {

  // additional field logic

  return (
   <>
     <TextField name="firstName" label="Your first name" required/>
     <TextField name="middleName" label="Your middle name" />
     <TextField name="lastName" label="Your last name" required/>
     <SelectField name="suffix" label="Suffix">
       <option />
       <option />
     </SelectField> 
   </>
  );
};
```

## Considerations
- [design.va.gov name guidance](https://design.va.gov/patterns/form-patterns#name)
- Validation messages:
  - `required`: Please enter a first/last name

## Tasks
- Write a `FullNameField` form field that meets the criteria above
- Write tests to ensure the field does what it's intended to

## Acceptance Criteria
- [ ] above tasks are complete
- [ ] PR into va-forms-system-core has been merged

**Comment by taylorkaren** [comment] 2022-03-30 12:21
Duplicate of #219.

**Closed by taylorkaren** 2022-03-30 12:21 UTC
Labels: VA Forms System Core
